### ISSUE TITLE
Validación formato de imagen

### ISSUE THREAD

**Issue by JotaMiller** [JotaMiller/appfb-megaiconos#1]
No valida los archivos de forma correcta,

creo que no funka lo de LowerCase, en el js cuando subes la imagen, ya que si tratas de subir una imagen JPG (con terminación en mayúsculas) te da error Dx

**Comment by JotaMiller** [comment]
Aparte de probar los issues de Github xD ejje

**Comment by kerosene** [comment]
jkajak dalee voy a revisarlo de ahí

**Comment by kerosene** [comment]
Jimbo pruébalo ahora, al parecer faltaba el lowercase en la segunda validación (la que se hace en img-process.php)
